#!/bin/bash
3, it should be 2 3, it should be 2 3, it should be 2 3, it should be 2 3, it should be 2 3, it should be 2 3, it should be 2 3, it should be 2 3, it should be 2 3, it should be 2 3, it should be 2 3,/
3, it should be 2 it should be 2 3, it should be 2 3, it should be 2 3, it should be 2 3, it should be 2 3, it should be 2 3, it should be 2 3, it should be 2 3, it should be 2 3, it should be 2 3,/

 



 

